// ActionCreator Types
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const FETCHED_POSTS = "FETCHED_POSTS";
export const FETCHING_POSTS_ERROR = "FETCHING_POSTS_ERROR";
export const IS_LOADING_POSTS = "IS_LOADING_POSTS";
export const IS_COMMENT_INSERTED = "IS_COMMENT_INSERTED";
export const COMMENT_INSERTION_ERROR = "COMMENT_INSERTION_ERROR";
export const IS_REACTION_UPSERTED = "IS_REACTION_UPSERTED";
export const REACTION_UPSERTION_ERROR = "REACTION_UPSERTION_ERROR";
export const PROFILE_PAGE_USER_DETAILS_AND_POSTS =
  "PROFILE_PAGE_USER_DETAILS_AND_POSTS";
export const PROFILE_PAGE_USER_DETAILS_AND_POSTS_ERROR =
  "PROFILE_PAGE_USER_DETAILS_AND_POSTS_ERROR";
